### ISSUE TITLE
Post titles & descriptions do not allow ampersands

### ISSUE THREAD

**Issue by Dainternetdude** [Technicalmc-xyz/technicalmc.xyz#14]

**Comment by Jackbaude** [comment]
Title are not allowed to have ampersands. https://developers.google.com/maps/documentation/urls/url-encoding. Will allow some punctuation in descriptions though.

**Comment by Dainternetdude** [comment]
perhaps titles can allow ampersands and other punctuation marks, and when they are transcribed to the URL, they can be removed, or the ampersands could be replaced with "and"

**Comment by Jackbaude** [comment]
Im not sure I understand a real good reason for the necessity of ampersands in titles. They are grammatically the same as "and". Unless you can convince me otherwise I think Im going to keep this issue closed.

**Comment by Dainternetdude** [comment]
Using ampersands allows longer titles to fit in the same space, & it allows the same length of titles to fit in a smaller space. This can be helpful in the journey towards supporting mobile users.
