### ISSUE TITLE
[Bug?] Only titles are linked to a page

### ISSUE THREAD

**Issue by Polarbub** [Technicalmc-xyz/technicalmc.xyz#16]
When I click on the body of an article's entry(?) (in black) it doesn't take me to said page. I need to click on the title (in red). I find this unitive and I think other people do too.
![Capture](https://user-images.githubusercontent.com/71790726/125680580-7e6b8e74-1aff-4aba-a7ab-dbe0597306dd.png)

**Comment by Jackbaude** [comment]
I agree. I would like to find a better way to display articles on the articles page, and I will probably scrap this idea all together.
