### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by Smugless** [Technicalmc-xyz/technicalmc.xyz#9]
I think that there should be an article outlining the general rules and style of the wiki. This would help contributors write articles in a way such that minimal editing is required. I would suggest adopting a style similar to the regular [Minecraft Wiki style guide](minecraft.fandom.com/wiki/Minecraft_Wiki:Style_guide).

**Comment by iDarkLightning** [comment]
That link tries to redirect on this domain and therefore does not work. [This should be the correct link](https://minecraft.fandom.com/wiki/Minecraft_Wiki:Style_guide)

**Comment by Jackbaude** [comment]
This is a pretty good first issue for anyone that knows any thing about nextjs and some HTML and minimal css styling. I can probably complete myself though
